export function getProvinces(){
	return provinces;
}

const provinces = [
	{id:"", value:"", "$empty": true },
    {id:"IT-AG", value:"Agrigento"},
    {id:"IT-AL", value:"Alessandria"},
    {id:"IT-AN", value:"Ancona"},
    {id:"IT-AO", value:"Aosta"},
    {id:"IT-AR", value:"Arezzo"},
    {id:"IT-AP", value:"Ascoli Piceno"},
    {id:"IT-AT", value:"Asti"},
    {id:"IT-AV", value:"Avellino"},
    {id:"IT-BA", value:"Bari"},
    {id:"IT-BT", value:"Barletta-Andria-Trani"},
    {id:"IT-BL", value:"Belluno"},
    {id:"IT-BN", value:"Benevento"},
    {id:"IT-BG", value:"Bergamo"},
    {id:"IT-BI", value:"Biella"},
    {id:"IT-BO", value:"Bologna"},
    {id:"IT-BZ", value:"Bolzano"},
    {id:"IT-BS", value:"Brescia"},
    {id:"IT-BR", value:"Brindisi"},
    {id:"IT-CA", value:"Cagliari"},
    {id:"IT-CL", value:"Caltanissetta"},
    {id:"IT-CB", value:"Campobasso"},
    {id:"IT-CI", value:"Carbonia-Iglesias"},
    {id:"IT-CE", value:"Caserta"},
    {id:"IT-CT", value:"Catania"},
    {id:"IT-CZ", value:"Catanzaro"},
    {id:"IT-CH", value:"Chieti"},
    {id:"IT-CO", value:"Como"},
    {id:"IT-CS", value:"Cosenza"},
    {id:"IT-CR", value:"Cremona"},
    {id:"IT-KR", value:"Crotone"},
    {id:"IT-CN", value:"Cuneo"},
    {id:"IT-EN", value:"Enna"},
    {id:"IT-FM", value:"Fermo"},
    {id:"IT-FE", value:"Ferrara"},
    {id:"IT-FI", value:"Firenze"},
    {id:"IT-FG", value:"Foggia"},
    {id:"IT-FC", value:"Forlì-Cesena"},
    {id:"IT-FR", value:"Frosinone"},
    {id:"IT-GE", value:"Genova"},
    {id:"IT-GO", value:"Gorizia"},
    {id:"IT-GR", value:"Grosseto"},
    {id:"IT-IM", value:"Imperia"},
    {id:"IT-IS", value:"Isernia"},
    {id:"IT-SP", value:"La Spezia"},
    {id:"IT-AQ", value:"L\"Aquila"},
    {id:"IT-LT", value:"Latina"},
    {id:"IT-LE", value:"Lecce"},
    {id:"IT-LC", value:"Lecco"},
    {id:"IT-LI", value:"Livorno"},
    {id:"IT-LO", value:"Lodi"},
    {id:"IT-LU", value:"Lucca"},
    {id:"IT-MC", value:"Macerata"},
    {id:"IT-MN", value:"Mantova"},
    {id:"IT-MS", value:"Massa-Carrara"},
    {id:"IT-MT", value:"Matera"},
    {id:"IT-ME", value:"Messina"},
    {id:"IT-MI", value:"Milano"},
    {id:"IT-MO", value:"Modena"},
    {id:"IT-MB", value:"Monza e della Brianza"},
    {id:"IT-NA", value:"Napoli"},
    {id:"IT-NO", value:"Novara"},
    {id:"IT-NU", value:"Nuoro"},
    {id:"IT-OT", value:"Olbia-Tempio"},
    {id:"IT-OR", value:"Oristano"},
    {id:"IT-PD", value:"Padova"},
    {id:"IT-PA", value:"Palermo"},
    {id:"IT-PR", value:"Parma"},
    {id:"IT-PV", value:"Pavia"},
    {id:"IT-PG", value:"Perugia"},
    {id:"IT-PU", value:"Pesaro e Urbino"},
    {id:"IT-PE", value:"Pescara"},
    {id:"IT-PC", value:"Piacenza"},
    {id:"IT-PI", value:"Pisa"},
    {id:"IT-PT", value:"Pistoia"},
    {id:"IT-PN", value:"Pordenone"},
    {id:"IT-PZ", value:"Potenza"},
    {id:"IT-PO", value:"Prato"},
    {id:"IT-RG", value:"Ragusa"},
    {id:"IT-RA", value:"Ravenna"},
    {id:"IT-RC", value:"Reggio Calabria"},
    {id:"IT-RE", value:"Reggio Emilia"},
    {id:"IT-RI", value:"Rieti"},
    {id:"IT-RN", value:"Rimini"},
    {id:"IT-RM", value:"Roma"},
    {id:"IT-RO", value:"Rovigo"},
    {id:"IT-SA", value:"Salerno"},
    {id:"IT-VS", value:"Medio Campidano"},
    {id:"IT-SS", value:"Sassari"},
    {id:"IT-SV", value:"Savona"},
    {id:"IT-SI", value:"Siena"},
    {id:"IT-SR", value:"Siracusa"},
    {id:"IT-SO", value:"Sondrio"},
    {id:"IT-TA", value:"Taranto"},
    {id:"IT-TE", value:"Teramo"},
    {id:"IT-TR", value:"Terni"},
    {id:"IT-TO", value:"Torino"},
    {id:"IT-OG", value:"Ogliastra"},
    {id:"IT-TP", value:"Trapani"},
    {id:"IT-TN", value:"Trento"},
    {id:"IT-TV", value:"Treviso"},
    {id:"IT-TS", value:"Trieste"},
    {id:"IT-UD", value:"Udine"},
    {id:"IT-VA", value:"Varese"},
    {id:"IT-VE", value:"Venezia"},
    {id:"IT-VB", value:"Verbano-Cusio-Ossola"},
    {id:"IT-VC", value:"Vercelli"},
    {id:"IT-VR", value:"Verona"},
    {id:"IT-VV", value:"Vibo Valentia"},
    {id:"IT-VI", value:"Vicenza"},
    {id:"IT-VT", value:"Viterbo"}
];